server:
  port: 8065
spring:
  application:
    name: sentinel-client
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.97.85:8848
        username: nacos
        password: nacos
        namespace: dev
        group: SENTINEL_GROUP
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      datasource:
        flow-rules:
          nacos:
            server-addr: 162.14.97.85:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            namespace: dev
            data-type: json
            rule-type: flow
#        param-flow-rules:
#          nacos:
#            server-addr: 162.14.97.85:8848
#            dataId: ${spring.application.name}-param-flow-rules
#            groupId: SENTINEL_GROUP
#            namespace: dev
#            data-type: json
#            rule-type: flow