// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

public final class CrsService {
  private CrsService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginParams_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginParams_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PublicKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PublicKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Token_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuestRoom_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GuestRoom_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HotelDescriptiveContent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HotelDescriptiveContent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushRoomTypeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushRoomTypeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushRoomTypeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushRoomTypeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomTypeSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomTypeSegment_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Property_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushRoomVolumesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushRoomVolumesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PushRoomVolumesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PushRoomVolumesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tpms.proto\032\033google/protobuf/empty.proto" +
      "\032\037google/protobuf/timestamp.proto\"-\n\013Log" +
      "inParams\022\014\n\004code\030\001 \001(\t\022\020\n\010singText\030\002 \001(\t" +
      "\"$\n\005Error\022\r\n\005error\030\001 \001(\t\022\014\n\004type\030\002 \001(\005\"\030" +
      "\n\tPublicKey\022\013\n\003key\030\001 \001(\014\"$\n\005Token\022\016\n\006sta" +
      "tus\030\001 \001(\010\022\013\n\003jwt\030\002 \001(\014\"Z\n\tGuestRoom\022\014\n\004c" +
      "ode\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\022\024\n\014maxOccupa" +
      "ncy\030\003 \001(\005\022\027\n\017descriptiveText\030\004 \001(\t\"u\n\027Ho" +
      "telDescriptiveContent\022\021\n\tchainCode\030\001 \001(\t" +
      "\022\021\n\thotelCode\030\002 \001(\t\022\024\n\014languageCode\030\003 \001(" +
      "\t\022\036\n\nguestRooms\030\004 \003(\0132\n.GuestRoom\"\210\001\n\023Pu" +
      "shRoomTypeRequest\022\017\n\007version\030\001 \001(\001\022\027\n\006ta" +
      "rget\030\002 \001(\0162\007.Target\022:\n\030hotelDescriptiveC" +
      "ontents\030\003 \003(\0132\030.HotelDescriptiveContent\022" +
      "\013\n\003jwt\030\004 \001(\014\"\205\001\n\024PushRoomTypeResponse\022\017\n" +
      "\007version\030\001 \001(\001\022\027\n\006target\030\002 \001(\0162\007.Target\022" +
      "+\n\020resultStatusCode\030\003 \001(\0162\021.ResultStatus" +
      "Code\022\026\n\006errors\030\004 \003(\0132\006.Error\"?\n\017RoomType" +
      "Segment\022\024\n\014roomTypeCode\030\003 \001(\t\022\026\n\016roomsAv" +
      "ailable\030\004 \001(\t\"e\n\010Property\022-\n\tstartDate\030\001" +
      " \001(\0132\032.google.protobuf.Timestamp\022*\n\020room" +
      "TypeSegments\030\002 \003(\0132\020.RoomTypeSegment\"W\n\026" +
      "PushRoomVolumesRequest\022\021\n\thotelCode\030\001 \001(" +
      "\t\022\035\n\nproperties\030\002 \003(\0132\t.Property\022\013\n\003jwt\030" +
      "\003 \001(\014\"F\n\027PushRoomVolumesResponse\022+\n\020resu" +
      "ltStatusCode\030\001 \001(\0162\021.ResultStatusCode*\"\n" +
      "\006Target\022\016\n\nProduction\020\000\022\010\n\004Test\020\001*+\n\020Res" +
      "ultStatusCode\022\013\n\007Success\020\000\022\n\n\006Errors\020\0012\355" +
      "\001\n\rCrsServerGrpc\0224\n\014GetPublicKey\022\026.googl" +
      "e.protobuf.Empty\032\n.PublicKey\"\000\022\037\n\005Login\022" +
      "\014.LoginParams\032\006.Token\"\000\022=\n\014PushRoomType\022" +
      "\024.PushRoomTypeRequest\032\025.PushRoomTypeResp" +
      "onse\"\000\022F\n\017PushRoomVolumes\022\027.PushRoomVolu" +
      "mesRequest\032\030.PushRoomVolumesResponse\"\000B*" +
      "\n\032com.qmx.crs.rpc.grpc.protoB\nCrsService" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_LoginParams_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginParams_descriptor,
        new java.lang.String[] { "Code", "SingText", });
    internal_static_Error_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Error_descriptor,
        new java.lang.String[] { "Error", "Type", });
    internal_static_PublicKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PublicKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PublicKey_descriptor,
        new java.lang.String[] { "Key", });
    internal_static_Token_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Token_descriptor,
        new java.lang.String[] { "Status", "Jwt", });
    internal_static_GuestRoom_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GuestRoom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GuestRoom_descriptor,
        new java.lang.String[] { "Code", "Quantity", "MaxOccupancy", "DescriptiveText", });
    internal_static_HotelDescriptiveContent_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_HotelDescriptiveContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HotelDescriptiveContent_descriptor,
        new java.lang.String[] { "ChainCode", "HotelCode", "LanguageCode", "GuestRooms", });
    internal_static_PushRoomTypeRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_PushRoomTypeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushRoomTypeRequest_descriptor,
        new java.lang.String[] { "Version", "Target", "HotelDescriptiveContents", "Jwt", });
    internal_static_PushRoomTypeResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_PushRoomTypeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushRoomTypeResponse_descriptor,
        new java.lang.String[] { "Version", "Target", "ResultStatusCode", "Errors", });
    internal_static_RoomTypeSegment_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_RoomTypeSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomTypeSegment_descriptor,
        new java.lang.String[] { "RoomTypeCode", "RoomsAvailable", });
    internal_static_Property_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Property_descriptor,
        new java.lang.String[] { "StartDate", "RoomTypeSegments", });
    internal_static_PushRoomVolumesRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_PushRoomVolumesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushRoomVolumesRequest_descriptor,
        new java.lang.String[] { "HotelCode", "Properties", "Jwt", });
    internal_static_PushRoomVolumesResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_PushRoomVolumesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PushRoomVolumesResponse_descriptor,
        new java.lang.String[] { "ResultStatusCode", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
