// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

/**
 * <pre>
 *酒店描述内容
 * </pre>
 *
 * Protobuf type {@code HotelDescriptiveContent}
 */
public final class HotelDescriptiveContent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HotelDescriptiveContent)
    HotelDescriptiveContentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HotelDescriptiveContent.newBuilder() to construct.
  private HotelDescriptiveContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HotelDescriptiveContent() {
    chainCode_ = "";
    hotelCode_ = "";
    languageCode_ = "";
    guestRooms_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new HotelDescriptiveContent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HotelDescriptiveContent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            chainCode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            hotelCode_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            languageCode_ = s;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              guestRooms_ = new java.util.ArrayList<com.qmx.crs.rpc.grpc.proto.GuestRoom>();
              mutable_bitField0_ |= 0x00000001;
            }
            guestRooms_.add(
                input.readMessage(com.qmx.crs.rpc.grpc.proto.GuestRoom.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        guestRooms_ = java.util.Collections.unmodifiableList(guestRooms_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_HotelDescriptiveContent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_HotelDescriptiveContent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.class, com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.Builder.class);
  }

  public static final int CHAINCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object chainCode_;
  /**
   * <pre>
   * 集团编码
   * </pre>
   *
   * <code>string chainCode = 1;</code>
   * @return The chainCode.
   */
  @java.lang.Override
  public java.lang.String getChainCode() {
    java.lang.Object ref = chainCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chainCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 集团编码
   * </pre>
   *
   * <code>string chainCode = 1;</code>
   * @return The bytes for chainCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChainCodeBytes() {
    java.lang.Object ref = chainCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chainCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HOTELCODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object hotelCode_;
  /**
   * <pre>
   *酒店编码
   * </pre>
   *
   * <code>string hotelCode = 2;</code>
   * @return The hotelCode.
   */
  @java.lang.Override
  public java.lang.String getHotelCode() {
    java.lang.Object ref = hotelCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hotelCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *酒店编码
   * </pre>
   *
   * <code>string hotelCode = 2;</code>
   * @return The bytes for hotelCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHotelCodeBytes() {
    java.lang.Object ref = hotelCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hotelCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGECODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object languageCode_;
  /**
   * <pre>
   *静态消息的语言  zh-CN:中文   en-US:英文
   * </pre>
   *
   * <code>string languageCode = 3;</code>
   * @return The languageCode.
   */
  @java.lang.Override
  public java.lang.String getLanguageCode() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *静态消息的语言  zh-CN:中文   en-US:英文
   * </pre>
   *
   * <code>string languageCode = 3;</code>
   * @return The bytes for languageCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageCodeBytes() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GUESTROOMS_FIELD_NUMBER = 4;
  private java.util.List<com.qmx.crs.rpc.grpc.proto.GuestRoom> guestRooms_;
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.qmx.crs.rpc.grpc.proto.GuestRoom> getGuestRoomsList() {
    return guestRooms_;
  }
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder> 
      getGuestRoomsOrBuilderList() {
    return guestRooms_;
  }
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  @java.lang.Override
  public int getGuestRoomsCount() {
    return guestRooms_.size();
  }
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  @java.lang.Override
  public com.qmx.crs.rpc.grpc.proto.GuestRoom getGuestRooms(int index) {
    return guestRooms_.get(index);
  }
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  @java.lang.Override
  public com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder getGuestRoomsOrBuilder(
      int index) {
    return guestRooms_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chainCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hotelCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, hotelCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, languageCode_);
    }
    for (int i = 0; i < guestRooms_.size(); i++) {
      output.writeMessage(4, guestRooms_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(chainCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chainCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hotelCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, hotelCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(languageCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, languageCode_);
    }
    for (int i = 0; i < guestRooms_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, guestRooms_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent)) {
      return super.equals(obj);
    }
    com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent other = (com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent) obj;

    if (!getChainCode()
        .equals(other.getChainCode())) return false;
    if (!getHotelCode()
        .equals(other.getHotelCode())) return false;
    if (!getLanguageCode()
        .equals(other.getLanguageCode())) return false;
    if (!getGuestRoomsList()
        .equals(other.getGuestRoomsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHAINCODE_FIELD_NUMBER;
    hash = (53 * hash) + getChainCode().hashCode();
    hash = (37 * hash) + HOTELCODE_FIELD_NUMBER;
    hash = (53 * hash) + getHotelCode().hashCode();
    hash = (37 * hash) + LANGUAGECODE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageCode().hashCode();
    if (getGuestRoomsCount() > 0) {
      hash = (37 * hash) + GUESTROOMS_FIELD_NUMBER;
      hash = (53 * hash) + getGuestRoomsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *酒店描述内容
   * </pre>
   *
   * Protobuf type {@code HotelDescriptiveContent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HotelDescriptiveContent)
      com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_HotelDescriptiveContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_HotelDescriptiveContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.class, com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.Builder.class);
    }

    // Construct using com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getGuestRoomsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      chainCode_ = "";

      hotelCode_ = "";

      languageCode_ = "";

      if (guestRoomsBuilder_ == null) {
        guestRooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        guestRoomsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_HotelDescriptiveContent_descriptor;
    }

    @java.lang.Override
    public com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent getDefaultInstanceForType() {
      return com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.getDefaultInstance();
    }

    @java.lang.Override
    public com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent build() {
      com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent buildPartial() {
      com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent result = new com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent(this);
      int from_bitField0_ = bitField0_;
      result.chainCode_ = chainCode_;
      result.hotelCode_ = hotelCode_;
      result.languageCode_ = languageCode_;
      if (guestRoomsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          guestRooms_ = java.util.Collections.unmodifiableList(guestRooms_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.guestRooms_ = guestRooms_;
      } else {
        result.guestRooms_ = guestRoomsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent) {
        return mergeFrom((com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent other) {
      if (other == com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent.getDefaultInstance()) return this;
      if (!other.getChainCode().isEmpty()) {
        chainCode_ = other.chainCode_;
        onChanged();
      }
      if (!other.getHotelCode().isEmpty()) {
        hotelCode_ = other.hotelCode_;
        onChanged();
      }
      if (!other.getLanguageCode().isEmpty()) {
        languageCode_ = other.languageCode_;
        onChanged();
      }
      if (guestRoomsBuilder_ == null) {
        if (!other.guestRooms_.isEmpty()) {
          if (guestRooms_.isEmpty()) {
            guestRooms_ = other.guestRooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureGuestRoomsIsMutable();
            guestRooms_.addAll(other.guestRooms_);
          }
          onChanged();
        }
      } else {
        if (!other.guestRooms_.isEmpty()) {
          if (guestRoomsBuilder_.isEmpty()) {
            guestRoomsBuilder_.dispose();
            guestRoomsBuilder_ = null;
            guestRooms_ = other.guestRooms_;
            bitField0_ = (bitField0_ & ~0x00000001);
            guestRoomsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getGuestRoomsFieldBuilder() : null;
          } else {
            guestRoomsBuilder_.addAllMessages(other.guestRooms_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object chainCode_ = "";
    /**
     * <pre>
     * 集团编码
     * </pre>
     *
     * <code>string chainCode = 1;</code>
     * @return The chainCode.
     */
    public java.lang.String getChainCode() {
      java.lang.Object ref = chainCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chainCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 集团编码
     * </pre>
     *
     * <code>string chainCode = 1;</code>
     * @return The bytes for chainCode.
     */
    public com.google.protobuf.ByteString
        getChainCodeBytes() {
      java.lang.Object ref = chainCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chainCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 集团编码
     * </pre>
     *
     * <code>string chainCode = 1;</code>
     * @param value The chainCode to set.
     * @return This builder for chaining.
     */
    public Builder setChainCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chainCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 集团编码
     * </pre>
     *
     * <code>string chainCode = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChainCode() {
      
      chainCode_ = getDefaultInstance().getChainCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 集团编码
     * </pre>
     *
     * <code>string chainCode = 1;</code>
     * @param value The bytes for chainCode to set.
     * @return This builder for chaining.
     */
    public Builder setChainCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chainCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hotelCode_ = "";
    /**
     * <pre>
     *酒店编码
     * </pre>
     *
     * <code>string hotelCode = 2;</code>
     * @return The hotelCode.
     */
    public java.lang.String getHotelCode() {
      java.lang.Object ref = hotelCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hotelCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *酒店编码
     * </pre>
     *
     * <code>string hotelCode = 2;</code>
     * @return The bytes for hotelCode.
     */
    public com.google.protobuf.ByteString
        getHotelCodeBytes() {
      java.lang.Object ref = hotelCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hotelCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *酒店编码
     * </pre>
     *
     * <code>string hotelCode = 2;</code>
     * @param value The hotelCode to set.
     * @return This builder for chaining.
     */
    public Builder setHotelCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hotelCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *酒店编码
     * </pre>
     *
     * <code>string hotelCode = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHotelCode() {
      
      hotelCode_ = getDefaultInstance().getHotelCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *酒店编码
     * </pre>
     *
     * <code>string hotelCode = 2;</code>
     * @param value The bytes for hotelCode to set.
     * @return This builder for chaining.
     */
    public Builder setHotelCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hotelCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object languageCode_ = "";
    /**
     * <pre>
     *静态消息的语言  zh-CN:中文   en-US:英文
     * </pre>
     *
     * <code>string languageCode = 3;</code>
     * @return The languageCode.
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *静态消息的语言  zh-CN:中文   en-US:英文
     * </pre>
     *
     * <code>string languageCode = 3;</code>
     * @return The bytes for languageCode.
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *静态消息的语言  zh-CN:中文   en-US:英文
     * </pre>
     *
     * <code>string languageCode = 3;</code>
     * @param value The languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      languageCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *静态消息的语言  zh-CN:中文   en-US:英文
     * </pre>
     *
     * <code>string languageCode = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguageCode() {
      
      languageCode_ = getDefaultInstance().getLanguageCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *静态消息的语言  zh-CN:中文   en-US:英文
     * </pre>
     *
     * <code>string languageCode = 3;</code>
     * @param value The bytes for languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      languageCode_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.qmx.crs.rpc.grpc.proto.GuestRoom> guestRooms_ =
      java.util.Collections.emptyList();
    private void ensureGuestRoomsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        guestRooms_ = new java.util.ArrayList<com.qmx.crs.rpc.grpc.proto.GuestRoom>(guestRooms_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.qmx.crs.rpc.grpc.proto.GuestRoom, com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder, com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder> guestRoomsBuilder_;

    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public java.util.List<com.qmx.crs.rpc.grpc.proto.GuestRoom> getGuestRoomsList() {
      if (guestRoomsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(guestRooms_);
      } else {
        return guestRoomsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public int getGuestRoomsCount() {
      if (guestRoomsBuilder_ == null) {
        return guestRooms_.size();
      } else {
        return guestRoomsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.GuestRoom getGuestRooms(int index) {
      if (guestRoomsBuilder_ == null) {
        return guestRooms_.get(index);
      } else {
        return guestRoomsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder setGuestRooms(
        int index, com.qmx.crs.rpc.grpc.proto.GuestRoom value) {
      if (guestRoomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGuestRoomsIsMutable();
        guestRooms_.set(index, value);
        onChanged();
      } else {
        guestRoomsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder setGuestRooms(
        int index, com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder builderForValue) {
      if (guestRoomsBuilder_ == null) {
        ensureGuestRoomsIsMutable();
        guestRooms_.set(index, builderForValue.build());
        onChanged();
      } else {
        guestRoomsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder addGuestRooms(com.qmx.crs.rpc.grpc.proto.GuestRoom value) {
      if (guestRoomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGuestRoomsIsMutable();
        guestRooms_.add(value);
        onChanged();
      } else {
        guestRoomsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder addGuestRooms(
        int index, com.qmx.crs.rpc.grpc.proto.GuestRoom value) {
      if (guestRoomsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGuestRoomsIsMutable();
        guestRooms_.add(index, value);
        onChanged();
      } else {
        guestRoomsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder addGuestRooms(
        com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder builderForValue) {
      if (guestRoomsBuilder_ == null) {
        ensureGuestRoomsIsMutable();
        guestRooms_.add(builderForValue.build());
        onChanged();
      } else {
        guestRoomsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder addGuestRooms(
        int index, com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder builderForValue) {
      if (guestRoomsBuilder_ == null) {
        ensureGuestRoomsIsMutable();
        guestRooms_.add(index, builderForValue.build());
        onChanged();
      } else {
        guestRoomsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder addAllGuestRooms(
        java.lang.Iterable<? extends com.qmx.crs.rpc.grpc.proto.GuestRoom> values) {
      if (guestRoomsBuilder_ == null) {
        ensureGuestRoomsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, guestRooms_);
        onChanged();
      } else {
        guestRoomsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder clearGuestRooms() {
      if (guestRoomsBuilder_ == null) {
        guestRooms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        guestRoomsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public Builder removeGuestRooms(int index) {
      if (guestRoomsBuilder_ == null) {
        ensureGuestRoomsIsMutable();
        guestRooms_.remove(index);
        onChanged();
      } else {
        guestRoomsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder getGuestRoomsBuilder(
        int index) {
      return getGuestRoomsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder getGuestRoomsOrBuilder(
        int index) {
      if (guestRoomsBuilder_ == null) {
        return guestRooms_.get(index);  } else {
        return guestRoomsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public java.util.List<? extends com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder> 
         getGuestRoomsOrBuilderList() {
      if (guestRoomsBuilder_ != null) {
        return guestRoomsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(guestRooms_);
      }
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder addGuestRoomsBuilder() {
      return getGuestRoomsFieldBuilder().addBuilder(
          com.qmx.crs.rpc.grpc.proto.GuestRoom.getDefaultInstance());
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder addGuestRoomsBuilder(
        int index) {
      return getGuestRoomsFieldBuilder().addBuilder(
          index, com.qmx.crs.rpc.grpc.proto.GuestRoom.getDefaultInstance());
    }
    /**
     * <code>repeated .GuestRoom guestRooms = 4;</code>
     */
    public java.util.List<com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder> 
         getGuestRoomsBuilderList() {
      return getGuestRoomsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.qmx.crs.rpc.grpc.proto.GuestRoom, com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder, com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder> 
        getGuestRoomsFieldBuilder() {
      if (guestRoomsBuilder_ == null) {
        guestRoomsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.qmx.crs.rpc.grpc.proto.GuestRoom, com.qmx.crs.rpc.grpc.proto.GuestRoom.Builder, com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder>(
                guestRooms_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        guestRooms_ = null;
      }
      return guestRoomsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HotelDescriptiveContent)
  }

  // @@protoc_insertion_point(class_scope:HotelDescriptiveContent)
  private static final com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent();
  }

  public static com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HotelDescriptiveContent>
      PARSER = new com.google.protobuf.AbstractParser<HotelDescriptiveContent>() {
    @java.lang.Override
    public HotelDescriptiveContent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HotelDescriptiveContent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HotelDescriptiveContent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HotelDescriptiveContent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qmx.crs.rpc.grpc.proto.HotelDescriptiveContent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

