// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

public interface HotelDescriptiveContentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HotelDescriptiveContent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 集团编码
   * </pre>
   *
   * <code>string chainCode = 1;</code>
   * @return The chainCode.
   */
  java.lang.String getChainCode();
  /**
   * <pre>
   * 集团编码
   * </pre>
   *
   * <code>string chainCode = 1;</code>
   * @return The bytes for chainCode.
   */
  com.google.protobuf.ByteString
      getChainCodeBytes();

  /**
   * <pre>
   *酒店编码
   * </pre>
   *
   * <code>string hotelCode = 2;</code>
   * @return The hotelCode.
   */
  java.lang.String getHotelCode();
  /**
   * <pre>
   *酒店编码
   * </pre>
   *
   * <code>string hotelCode = 2;</code>
   * @return The bytes for hotelCode.
   */
  com.google.protobuf.ByteString
      getHotelCodeBytes();

  /**
   * <pre>
   *静态消息的语言  zh-CN:中文   en-US:英文
   * </pre>
   *
   * <code>string languageCode = 3;</code>
   * @return The languageCode.
   */
  java.lang.String getLanguageCode();
  /**
   * <pre>
   *静态消息的语言  zh-CN:中文   en-US:英文
   * </pre>
   *
   * <code>string languageCode = 3;</code>
   * @return The bytes for languageCode.
   */
  com.google.protobuf.ByteString
      getLanguageCodeBytes();

  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  java.util.List<com.qmx.crs.rpc.grpc.proto.GuestRoom> 
      getGuestRoomsList();
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  com.qmx.crs.rpc.grpc.proto.GuestRoom getGuestRooms(int index);
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  int getGuestRoomsCount();
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  java.util.List<? extends com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder> 
      getGuestRoomsOrBuilderList();
  /**
   * <code>repeated .GuestRoom guestRooms = 4;</code>
   */
  com.qmx.crs.rpc.grpc.proto.GuestRoomOrBuilder getGuestRoomsOrBuilder(
      int index);
}
