// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

public interface PropertyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Property)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *日期
   * </pre>
   *
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   * @return Whether the startDate field is set.
   */
  boolean hasStartDate();
  /**
   * <pre>
   *日期
   * </pre>
   *
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   * @return The startDate.
   */
  com.google.protobuf.Timestamp getStartDate();
  /**
   * <pre>
   *日期
   * </pre>
   *
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder();

  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  java.util.List<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment> 
      getRoomTypeSegmentsList();
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  com.qmx.crs.rpc.grpc.proto.RoomTypeSegment getRoomTypeSegments(int index);
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  int getRoomTypeSegmentsCount();
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  java.util.List<? extends com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder> 
      getRoomTypeSegmentsOrBuilderList();
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder getRoomTypeSegmentsOrBuilder(
      int index);
}
