// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

/**
 * <pre>
 *日期与房型可用房量数组
 * </pre>
 *
 * Protobuf type {@code Property}
 */
public final class Property extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Property)
    PropertyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Property.newBuilder() to construct.
  private Property(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Property() {
    roomTypeSegments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Property();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Property(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (startDate_ != null) {
              subBuilder = startDate_.toBuilder();
            }
            startDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startDate_);
              startDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              roomTypeSegments_ = new java.util.ArrayList<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment>();
              mutable_bitField0_ |= 0x00000001;
            }
            roomTypeSegments_.add(
                input.readMessage(com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        roomTypeSegments_ = java.util.Collections.unmodifiableList(roomTypeSegments_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_Property_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_Property_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.qmx.crs.rpc.grpc.proto.Property.class, com.qmx.crs.rpc.grpc.proto.Property.Builder.class);
  }

  public static final int STARTDATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp startDate_;
  /**
   * <pre>
   *日期
   * </pre>
   *
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   * @return Whether the startDate field is set.
   */
  @java.lang.Override
  public boolean hasStartDate() {
    return startDate_ != null;
  }
  /**
   * <pre>
   *日期
   * </pre>
   *
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   * @return The startDate.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getStartDate() {
    return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
  }
  /**
   * <pre>
   *日期
   * </pre>
   *
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
    return getStartDate();
  }

  public static final int ROOMTYPESEGMENTS_FIELD_NUMBER = 2;
  private java.util.List<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment> roomTypeSegments_;
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment> getRoomTypeSegmentsList() {
    return roomTypeSegments_;
  }
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder> 
      getRoomTypeSegmentsOrBuilderList() {
    return roomTypeSegments_;
  }
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  @java.lang.Override
  public int getRoomTypeSegmentsCount() {
    return roomTypeSegments_.size();
  }
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  @java.lang.Override
  public com.qmx.crs.rpc.grpc.proto.RoomTypeSegment getRoomTypeSegments(int index) {
    return roomTypeSegments_.get(index);
  }
  /**
   * <pre>
   *房型可用房量数组
   * </pre>
   *
   * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
   */
  @java.lang.Override
  public com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder getRoomTypeSegmentsOrBuilder(
      int index) {
    return roomTypeSegments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startDate_ != null) {
      output.writeMessage(1, getStartDate());
    }
    for (int i = 0; i < roomTypeSegments_.size(); i++) {
      output.writeMessage(2, roomTypeSegments_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartDate());
    }
    for (int i = 0; i < roomTypeSegments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, roomTypeSegments_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.qmx.crs.rpc.grpc.proto.Property)) {
      return super.equals(obj);
    }
    com.qmx.crs.rpc.grpc.proto.Property other = (com.qmx.crs.rpc.grpc.proto.Property) obj;

    if (hasStartDate() != other.hasStartDate()) return false;
    if (hasStartDate()) {
      if (!getStartDate()
          .equals(other.getStartDate())) return false;
    }
    if (!getRoomTypeSegmentsList()
        .equals(other.getRoomTypeSegmentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartDate()) {
      hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (getRoomTypeSegmentsCount() > 0) {
      hash = (37 * hash) + ROOMTYPESEGMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getRoomTypeSegmentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.qmx.crs.rpc.grpc.proto.Property parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.qmx.crs.rpc.grpc.proto.Property prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *日期与房型可用房量数组
   * </pre>
   *
   * Protobuf type {@code Property}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Property)
      com.qmx.crs.rpc.grpc.proto.PropertyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_Property_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_Property_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.qmx.crs.rpc.grpc.proto.Property.class, com.qmx.crs.rpc.grpc.proto.Property.Builder.class);
    }

    // Construct using com.qmx.crs.rpc.grpc.proto.Property.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRoomTypeSegmentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startDateBuilder_ == null) {
        startDate_ = null;
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }
      if (roomTypeSegmentsBuilder_ == null) {
        roomTypeSegments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        roomTypeSegmentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.qmx.crs.rpc.grpc.proto.CrsService.internal_static_Property_descriptor;
    }

    @java.lang.Override
    public com.qmx.crs.rpc.grpc.proto.Property getDefaultInstanceForType() {
      return com.qmx.crs.rpc.grpc.proto.Property.getDefaultInstance();
    }

    @java.lang.Override
    public com.qmx.crs.rpc.grpc.proto.Property build() {
      com.qmx.crs.rpc.grpc.proto.Property result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.qmx.crs.rpc.grpc.proto.Property buildPartial() {
      com.qmx.crs.rpc.grpc.proto.Property result = new com.qmx.crs.rpc.grpc.proto.Property(this);
      int from_bitField0_ = bitField0_;
      if (startDateBuilder_ == null) {
        result.startDate_ = startDate_;
      } else {
        result.startDate_ = startDateBuilder_.build();
      }
      if (roomTypeSegmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          roomTypeSegments_ = java.util.Collections.unmodifiableList(roomTypeSegments_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.roomTypeSegments_ = roomTypeSegments_;
      } else {
        result.roomTypeSegments_ = roomTypeSegmentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.qmx.crs.rpc.grpc.proto.Property) {
        return mergeFrom((com.qmx.crs.rpc.grpc.proto.Property)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.qmx.crs.rpc.grpc.proto.Property other) {
      if (other == com.qmx.crs.rpc.grpc.proto.Property.getDefaultInstance()) return this;
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (roomTypeSegmentsBuilder_ == null) {
        if (!other.roomTypeSegments_.isEmpty()) {
          if (roomTypeSegments_.isEmpty()) {
            roomTypeSegments_ = other.roomTypeSegments_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRoomTypeSegmentsIsMutable();
            roomTypeSegments_.addAll(other.roomTypeSegments_);
          }
          onChanged();
        }
      } else {
        if (!other.roomTypeSegments_.isEmpty()) {
          if (roomTypeSegmentsBuilder_.isEmpty()) {
            roomTypeSegmentsBuilder_.dispose();
            roomTypeSegmentsBuilder_ = null;
            roomTypeSegments_ = other.roomTypeSegments_;
            bitField0_ = (bitField0_ & ~0x00000001);
            roomTypeSegmentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getRoomTypeSegmentsFieldBuilder() : null;
          } else {
            roomTypeSegmentsBuilder_.addAllMessages(other.roomTypeSegments_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.qmx.crs.rpc.grpc.proto.Property parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.qmx.crs.rpc.grpc.proto.Property) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Timestamp startDate_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startDateBuilder_;
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     * @return Whether the startDate field is set.
     */
    public boolean hasStartDate() {
      return startDateBuilder_ != null || startDate_ != null;
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     * @return The startDate.
     */
    public com.google.protobuf.Timestamp getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder setStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
        onChanged();
      } else {
        startDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder setStartDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
        onChanged();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder mergeStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (startDate_ != null) {
          startDate_ =
            com.google.protobuf.Timestamp.newBuilder(startDate_).mergeFrom(value).buildPartial();
        } else {
          startDate_ = value;
        }
        onChanged();
      } else {
        startDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder clearStartDate() {
      if (startDateBuilder_ == null) {
        startDate_ = null;
        onChanged();
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartDateBuilder() {
      
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private java.util.List<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment> roomTypeSegments_ =
      java.util.Collections.emptyList();
    private void ensureRoomTypeSegmentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        roomTypeSegments_ = new java.util.ArrayList<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment>(roomTypeSegments_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.qmx.crs.rpc.grpc.proto.RoomTypeSegment, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder, com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder> roomTypeSegmentsBuilder_;

    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public java.util.List<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment> getRoomTypeSegmentsList() {
      if (roomTypeSegmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(roomTypeSegments_);
      } else {
        return roomTypeSegmentsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public int getRoomTypeSegmentsCount() {
      if (roomTypeSegmentsBuilder_ == null) {
        return roomTypeSegments_.size();
      } else {
        return roomTypeSegmentsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.RoomTypeSegment getRoomTypeSegments(int index) {
      if (roomTypeSegmentsBuilder_ == null) {
        return roomTypeSegments_.get(index);
      } else {
        return roomTypeSegmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder setRoomTypeSegments(
        int index, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment value) {
      if (roomTypeSegmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.set(index, value);
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder setRoomTypeSegments(
        int index, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder builderForValue) {
      if (roomTypeSegmentsBuilder_ == null) {
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.set(index, builderForValue.build());
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder addRoomTypeSegments(com.qmx.crs.rpc.grpc.proto.RoomTypeSegment value) {
      if (roomTypeSegmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.add(value);
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder addRoomTypeSegments(
        int index, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment value) {
      if (roomTypeSegmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.add(index, value);
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder addRoomTypeSegments(
        com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder builderForValue) {
      if (roomTypeSegmentsBuilder_ == null) {
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.add(builderForValue.build());
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder addRoomTypeSegments(
        int index, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder builderForValue) {
      if (roomTypeSegmentsBuilder_ == null) {
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.add(index, builderForValue.build());
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder addAllRoomTypeSegments(
        java.lang.Iterable<? extends com.qmx.crs.rpc.grpc.proto.RoomTypeSegment> values) {
      if (roomTypeSegmentsBuilder_ == null) {
        ensureRoomTypeSegmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, roomTypeSegments_);
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder clearRoomTypeSegments() {
      if (roomTypeSegmentsBuilder_ == null) {
        roomTypeSegments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public Builder removeRoomTypeSegments(int index) {
      if (roomTypeSegmentsBuilder_ == null) {
        ensureRoomTypeSegmentsIsMutable();
        roomTypeSegments_.remove(index);
        onChanged();
      } else {
        roomTypeSegmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder getRoomTypeSegmentsBuilder(
        int index) {
      return getRoomTypeSegmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder getRoomTypeSegmentsOrBuilder(
        int index) {
      if (roomTypeSegmentsBuilder_ == null) {
        return roomTypeSegments_.get(index);  } else {
        return roomTypeSegmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public java.util.List<? extends com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder> 
         getRoomTypeSegmentsOrBuilderList() {
      if (roomTypeSegmentsBuilder_ != null) {
        return roomTypeSegmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(roomTypeSegments_);
      }
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder addRoomTypeSegmentsBuilder() {
      return getRoomTypeSegmentsFieldBuilder().addBuilder(
          com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.getDefaultInstance());
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder addRoomTypeSegmentsBuilder(
        int index) {
      return getRoomTypeSegmentsFieldBuilder().addBuilder(
          index, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.getDefaultInstance());
    }
    /**
     * <pre>
     *房型可用房量数组
     * </pre>
     *
     * <code>repeated .RoomTypeSegment roomTypeSegments = 2;</code>
     */
    public java.util.List<com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder> 
         getRoomTypeSegmentsBuilderList() {
      return getRoomTypeSegmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.qmx.crs.rpc.grpc.proto.RoomTypeSegment, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder, com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder> 
        getRoomTypeSegmentsFieldBuilder() {
      if (roomTypeSegmentsBuilder_ == null) {
        roomTypeSegmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.qmx.crs.rpc.grpc.proto.RoomTypeSegment, com.qmx.crs.rpc.grpc.proto.RoomTypeSegment.Builder, com.qmx.crs.rpc.grpc.proto.RoomTypeSegmentOrBuilder>(
                roomTypeSegments_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        roomTypeSegments_ = null;
      }
      return roomTypeSegmentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Property)
  }

  // @@protoc_insertion_point(class_scope:Property)
  private static final com.qmx.crs.rpc.grpc.proto.Property DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.qmx.crs.rpc.grpc.proto.Property();
  }

  public static com.qmx.crs.rpc.grpc.proto.Property getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Property>
      PARSER = new com.google.protobuf.AbstractParser<Property>() {
    @java.lang.Override
    public Property parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Property(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Property> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Property> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.qmx.crs.rpc.grpc.proto.Property getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

