// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

public interface PushRoomTypeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PushRoomTypeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *消息版本
   * </pre>
   *
   * <code>double version = 1;</code>
   * @return The version.
   */
  double getVersion();

  /**
   * <pre>
   *环境
   * </pre>
   *
   * <code>.Target target = 2;</code>
   * @return The enum numeric value on the wire for target.
   */
  int getTargetValue();
  /**
   * <pre>
   *环境
   * </pre>
   *
   * <code>.Target target = 2;</code>
   * @return The target.
   */
  com.qmx.crs.rpc.grpc.proto.Target getTarget();

  /**
   * <pre>
   *结果代码
   * </pre>
   *
   * <code>.ResultStatusCode resultStatusCode = 3;</code>
   * @return The enum numeric value on the wire for resultStatusCode.
   */
  int getResultStatusCodeValue();
  /**
   * <pre>
   *结果代码
   * </pre>
   *
   * <code>.ResultStatusCode resultStatusCode = 3;</code>
   * @return The resultStatusCode.
   */
  com.qmx.crs.rpc.grpc.proto.ResultStatusCode getResultStatusCode();

  /**
   * <pre>
   *错误信息列表
   * </pre>
   *
   * <code>repeated .Error errors = 4;</code>
   */
  java.util.List<com.qmx.crs.rpc.grpc.proto.Error> 
      getErrorsList();
  /**
   * <pre>
   *错误信息列表
   * </pre>
   *
   * <code>repeated .Error errors = 4;</code>
   */
  com.qmx.crs.rpc.grpc.proto.Error getErrors(int index);
  /**
   * <pre>
   *错误信息列表
   * </pre>
   *
   * <code>repeated .Error errors = 4;</code>
   */
  int getErrorsCount();
  /**
   * <pre>
   *错误信息列表
   * </pre>
   *
   * <code>repeated .Error errors = 4;</code>
   */
  java.util.List<? extends com.qmx.crs.rpc.grpc.proto.ErrorOrBuilder> 
      getErrorsOrBuilderList();
  /**
   * <pre>
   *错误信息列表
   * </pre>
   *
   * <code>repeated .Error errors = 4;</code>
   */
  com.qmx.crs.rpc.grpc.proto.ErrorOrBuilder getErrorsOrBuilder(
      int index);
}
