// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

public interface PushRoomVolumesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PushRoomVolumesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *推送结果
   * </pre>
   *
   * <code>.ResultStatusCode resultStatusCode = 1;</code>
   * @return The enum numeric value on the wire for resultStatusCode.
   */
  int getResultStatusCodeValue();
  /**
   * <pre>
   *推送结果
   * </pre>
   *
   * <code>.ResultStatusCode resultStatusCode = 1;</code>
   * @return The resultStatusCode.
   */
  com.qmx.crs.rpc.grpc.proto.ResultStatusCode getResultStatusCode();
}
