// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pms.proto

package com.qmx.crs.rpc.grpc.proto;

/**
 * Protobuf enum {@code ResultStatusCode}
 */
public enum ResultStatusCode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   *成功
   * </pre>
   *
   * <code>Success = 0;</code>
   */
  Success(0),
  /**
   * <pre>
   *失败
   * </pre>
   *
   * <code>Errors = 1;</code>
   */
  Errors(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   *成功
   * </pre>
   *
   * <code>Success = 0;</code>
   */
  public static final int Success_VALUE = 0;
  /**
   * <pre>
   *失败
   * </pre>
   *
   * <code>Errors = 1;</code>
   */
  public static final int Errors_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ResultStatusCode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ResultStatusCode forNumber(int value) {
    switch (value) {
      case 0: return Success;
      case 1: return Errors;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ResultStatusCode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ResultStatusCode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ResultStatusCode>() {
          public ResultStatusCode findValueByNumber(int number) {
            return ResultStatusCode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.qmx.crs.rpc.grpc.proto.CrsService.getDescriptor().getEnumTypes().get(1);
  }

  private static final ResultStatusCode[] VALUES = values();

  public static ResultStatusCode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ResultStatusCode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ResultStatusCode)
}

