server:
  port: 8065
spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: test-sentinel-nacos
  cloud:
    nacos:
      discovery:
        server-addr: 162.14.97.85
        port: 8848
        username: nacos
        password: nacos
        namespace: dev
        group: SENTINEL_GROUP
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8858
      datasource:
        dsl:
          nacos:
            server-addr: 162.14.97.85:8848
            data-id: ${spring.application.name}-flow-rules
            username: nacos
            password: nacos
            namespace: dev
            group-id: SENTINEL_GROUP
            rule-type: flow
            data-type: json