spring:
  application:
    name: simple-server-door
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 6003

dubbo:
  application:
    name: ${spring.application.name}
    logger: slf4j
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://162.14.97.85:8848
  metadata-report:
    address: nacos://162.14.97.85:8848
  consumer:
    validation: true
    timeout: 3000
    check: false
  scan:
    base-packages: club.zqprime.server.controller